# site settings
title: Ezra Newman
subtitle: Programmer, student, human
email: contact@ezranewman.com
description: I'm a high school student interested in cybersecurity, programming, backpacking, lighting design, sailing, community service, and more.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
email: public-contact-1@ezranewman.com
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ExtraE113
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/E113Extra

# build settings
markdown: kramdown

sass:
  style: compressed
